name = "RDE_Env"
uuid = "6fae0b71-e89e-4561-9656-794937ecd499"
authors = ["Kristian Holme"]
version = "0.0.1"

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
POMDPTools = "7588e00f-9cae-40de-98dc-e0c70c48cdd7"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
RDE = "1d57ab14-0807-4ee5-93aa-665821a12dfd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CircularArrays = "1"
DomainSets = "0"
Observables = "0"
POMDPTools = "1"
POMDPs = "1"
julia = "1.6"
