name = "RDE_Env"
uuid = "6fae0b71-e89e-4561-9656-794937ecd499"
version = "0.0.1"
authors = ["Kristian Holme"]

[deps]
CircularArrays = "7a955b69-7140-5f4e-a0ed-f168c5e2e749"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Drill = "49b37b9d-a8e6-4364-9144-4677bcb8a7f0"
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
DomainSets = "5b8099bc-c8ec-5219-889f-1d9e522a28bf"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
RDE = "1d57ab14-0807-4ee5-93aa-665821a12dfd"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[sources]
Drill = {rev = "main", url = "https://github.com/KristianHolme/Drill.jl"}
RDE = {rev = "main", url = "https://github.com/KristianHolme/RDE.jl"}

[compat]
CircularArrays = "1"
Colors = "0.13"
Drill = "0.0.1"
DiffEqCallbacks = "4.9"
DomainSets = "0"
LinearAlgebra = "1"
Logging = "1"
Makie = "0.24"
Observables = "0"
OrdinaryDiffEq = "6"
PrecompileTools = "1"
ProgressMeter = "1.10"
RDE = "0"
Random = "1"
SciMLBase = "2"
Statistics = "1"
julia = "1.10"
